(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  Script generated:  2023-08-02 16:41:49
  From session:  OpenUrl
  Captured on:  2023-08-02 16:39:35
  From server:  Server2016-0101_1920_1200
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

DoubleClick (Image:"ChromeIcon", WaitFor:10)
Click (Image:"Url", WaitFor:20)
TypeText "https://hotel.testplanisphere.dev",Return
WaitFor 20, "HOTELPLANISPHERE_Logo.png"
Click (Image:"ToJpnTopPage", WaitFor:20)

