to handle Validate_予約確認 
	WaitFor 8.0, "宿泊予約確認"
	WaitFor 8.0, "ThemeParkPgTiitle"
	
	Set the SearchRectangle to ("Name_A","Name_B")
	WaitFor 20, text:"MSYS 太郎様", language:"Japanese", validCharacters:"*", ignoreSpaces:"Yes"
	set the SearchRectangle to empty
	
	CaptureScreen {Name: "予約確認"}

end Validate_予約確認

to handle 予約する
	Click (Image:"この内容で予約する", WaitFor:20)
	WaitFor 8.0, "予約を完了しました"
	CaptureScreen {Name: "予約確認"}
	Click (Image:"Popup閉じる", WaitFor:10)
	
end 予約する
